### ISSUE TITLE
Typo in userguide

### ISSUE THREAD

**Issue by RenzoTascheri** [DLMtool/DLMtool_UserGuide#2]
Chapter 29. Section 29.3 ("Creating Example PMs and Plot").

Line: PMobj@Prob <- calcProb(PMobj@Stat) in example PM functions MeanB and MeanF 
should read:

PMobj@Prob <- calcProb(PMobj@Stat,MSEobj)

**Comment by AdrianHordyk** [comment]
Fixed - online userguide updated for Version 5.2+
